name: 图片融合并压缩
nodes:
  - id: blend
    uses: neuro.official/custom-image-blend-script
    with:
      mix_ratio: 50

  - id: compress
    uses: neuro.official/custom-1770146354922
    needs:
      - blend
    with:
      input: ${{ nodes.blend.outputs.output_base64 }}
      quality_num: 90
      lossless: false
